### ISSUE TITLE
pointing model is likely not included

### ISSUE THREAD

**Issue by EranOfek** [PolishookDavid/LAST_OCS#27] opened 2024-06-06 15:15 UTC
In the gledmagicwater branch, it seems that the point model is not included,
while it was applied in the previous stable branch used in the LAST observing run in March.

We see that in the gledmagicwater headers, ADRA and and ARA (as well as ADDec and ADec) are equal, while in the previous run they were different. The difference between these two parameters is the pointing model offset (taken from LAST_config/obs.PointingModel).
To verify this, it seems that the offset in astrometry between images taken in the March run and in the June run are consistent with the point model offsets.

Ruslan can add some examples.

**Comment by RuslanKonno** [comment] 2024-06-06 15:47
I was writing the same issue, so I'll just copypaste it here:

The data taken during the June nights of 2024-06-03 to 2024-06-05 show misalignment with reference images taken in March 2024. This is at least confirmed for mounts M1, M3, M6, M8. 

Inspecting the headers of the images, e.g.,

> /marvin/LAST.01.06.02/2024/06/03/proc/220200v0/LAST.01.06.02_20240603.220150.321_clear_1209_000_001_010_sci_coadd_Image_1.fits

shows that the mount A and AD coordinates are the same, implying that the full pointing correction was not applied. Example for the image above:

> M_ARA   =             229.5725 /                                                
> M_AHA   =              28.6867 /                                                
> M_ADEC  =              20.9185 /                                                
> M_ADRA  =             229.5725 /                                                
> M_ADHA  =              28.6867 /                                                
> M_ADDEC =              20.9185 /        

       

When registering the June images to the March reference images of the same field, the misalignment is clearly seen. Below is the reference image registered to the example new image. 

![Screenshot from 2024-06-06 18-41-47](https://github.com/PolishookDavid/LAST_OCS/assets/51087294/92e3c9ed-df39-480f-b412-20a80cffdfaa)

Measuring the misalignment (green lines in the image above) gives similar values to the missing pointing offset

Measured misalignment:
(Delta RA, Delta Dec) = ~(0.299, 0.428)

Offset given by the pointing model at (HA, Dec) = (26.668319,   27.098529)
(Delta RA, Delta Dec) = ~( -0.220345, -0.451985)

Mind I'm only measuring the absolute misalignment, so I'm ignoring the sign. Also, the offset is taken from the nearest coordinates in `obs.pointingModel.06_1.create.yml`, which is not exactly the same as the image coordinates, so the shown measured misalignment won't closely match the expected offset, they do agree in the leading order floating point position.

This is consistent with the misalignment seen in at least M1 as well.

**Comment by EastEriq** [comment] 2024-06-06 19:06
Note that there have been these two recent modifications to AstroPack, which could come (wrongly) into play here:
- https://github.com/EranOfek/AstroPack/issues/437
- https://github.com/EranOfek/AstroPack/issues/442

**Comment by EranOfek** [comment] 2024-06-06 19:20
Can you please provide more details into:
437 and 442.

**Comment by EastEriq** [comment] 2024-06-06 19:31
Details of what? The changes done and their original motivation are referenced there. This is why we use a linked ticked system and reference the commits pertinent to each issue.

**Comment by EastEriq** [comment] 2024-06-09 11:59
Seems that the problem was in a typo in `celestial.convert.j2000_toApparent` and `apparent_toJ2000` on the AstroPack side. We have now pushed the fix (https://github.com/EranOfek/AstroPack/commit/e4e875f0fd9ffd23fec30da2bb89f0a75dd77190), but the fix has still to be tested on sky. AstroPack should be pulled in the observatory but we are offline at the moment.

Please close when confirmed working.

**Comment by EastEriq** [comment] 2024-06-10 11:36
Confirmed solved in last nights images by Ruslan

**Closed by EastEriq** 2024-06-10 11:36 UTC
